Add dev-perl/Module-Build to DEPEND
Fix this QA message:
QA Notice: The ebuild uses Module::Build but doesn't depend on it.
ERROR: perl-gcpan/Text-Trim-1.02::splog-musicbrainz-mirror failed (configure phase):
Add dev-perl/Module-Build to DEPEND!